org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
mc_version=1.21
minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.200
neo_version_range=[21.1,)
loader_version_range=[4,)

create_version = 6.0.8-168
create_version_range=[6.0.8,)

registrate_version = MC1.21-1.3.0+67
ponder_version = 1.0.64
flywheel_version = 1.0.4-beta-21
jei_version = 19.21.2.313
curios_version = 9.5.1
sodium_version = 0.6.13

fusion_version = 1.2.4
fusion_version_range = [1.2.4,)

mod_id=slag
mod_name=Slag n' Embers
mod_license=All Rights Reserved
mod_version=1.0.3
mod_group_id=dev.lopyluna
mod_authors=LopyLuna
mod_description=A Modular Tool & Metallurgy System mod